# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

triangle_counter = 286
triangle_number = 1

def get_triangle_number(n)
	return (n**2 + n) / 2
end

pentagonal_counter = 165
pentagonal_number = 1

def get_pentagonal_number(n)
	return (3 * n**2 - n) / 2
end

hexagonal_counter = 143
hexagonal_number = 1

def get_hexagonal_number(n)
	return 2 * n**2 - n
end

found_match = false

while found_match == false
	triangle_number = get_triangle_number(triangle_counter)
	while triangle_number != pentagonal_number
		if triangle_number < pentagonal_number
			triangle_counter += 1
			triangle_number = get_triangle_number(triangle_counter)
		end
		if triangle_number > pentagonal_number
			pentagonal_counter += 1
			pentagonal_number = get_pentagonal_number(pentagonal_counter)
		end
	end
	while triangle_number > hexagonal_number
		hexagonal_counter += 1
		hexagonal_number = get_hexagonal_number(hexagonal_counter)
	end
	if pentagonal_number == hexagonal_number
		found_match = true
	else
		triangle_counter += 1
	end
end

puts triangle_number